# Deep Learning with PyTorch: A 60 Minute Blitz

This is me following along to the [tutorial from the official PyTorch website](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py). Note that I'm also taking some asides and detours as I type the code to investigate interesting detours as I seek to more fully understand the runtime.

The first thing that we need to do is import the torch library. This takes a fair amount of time. Fortunately, this is a one-time operation per session.

In [1]:
import torch

This Hello, World example initializes a new tensor of dimensinos `[5,3]` that contain random values from whatever the memory was before the call, i.e., it does not zero it out.

In [2]:
x = torch.empty(5, 3)
x

tensor([[8.4490e-39, 1.0102e-38, 9.0919e-39],
        [1.0102e-38, 8.9082e-39, 8.4489e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39],
        [9.2755e-39, 1.0286e-38, 9.0919e-39],
        [8.9082e-39, 9.2755e-39, 8.4490e-39]])

This next example constructs a tensor, but this time initialized to zeros:

In [3]:
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

You can also specify the _type_ of the zeros that you want, e.g., half precision floating point (which is interesting for its performance characteristics)

In [4]:
x = torch.zeros(5, 3, dtype=torch.half)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

You can also create it with explicit random values:

In [5]:
x = torch.rand(5, 3, dtype=torch.float)
x

tensor([[0.5992, 0.8103, 0.7118],
        [0.3897, 0.5566, 0.6124],
        [0.2514, 0.3906, 0.3700],
        [0.3143, 0.1902, 0.4016],
        [0.6071, 0.0894, 0.4809]])

But if you try and use a type that is only supported on GPUs, e.g., `torch.half`, it will throw an error because `torch.rand` by default will construct the type on the CPU:

In [6]:
x = torch.rand(5, 3, dtype=torch.half)
x

RuntimeError: _th_uniform_ not supported on CPUType for Half

So we solve this by first initializing a `cuda` device:

In [7]:
device = torch.device("cuda")
device

device(type='cuda')

We can pass the `cuda` device as a parameter to `torch.rand` which now constructs the tensor on the GPU successfully:

In [8]:
x = torch.rand(5, 3, device=device, dtype=torch.half)
x

tensor([[0.5308, 0.5234, 0.4890],
        [0.6890, 0.6074, 0.3242],
        [0.3281, 0.5093, 0.4951],
        [0.2864, 0.9121, 0.0216],
        [0.0818, 0.3625, 0.2754]], device='cuda:0', dtype=torch.float16)

In [9]:
3+3

6